In [2]:
import numpy

In [3]:
A = numpy.array([[-1, -1,  1,  0,  0,  0,  0,  0,  0,  0],
 [ 0,  1, -1,  1,  0,  0,  0,  0,  0,  0],
 [ 0,  0,  0, -1, -1,  1,  0,  0,  0,  0],
 [ 0,  0,  0, -1,  0,  0, -1,  1,  0,  0],
 [ 0,  0,  0,  1,  0,  0,  0, -1,  1,  0],
 [ 0,  0,  0,  0, -1,  0,  0,  0, -1,  1]])


In [5]:
v = numpy.array([-1,  1, -1, -1,  1, -1,  1,  1, -1,  1])

In [10]:
d1 = numpy.linalg.matrix_rank(A)

B = numpy.array([[-1, -1,  1,  0,  0,  0,  0,  0,  0,  0],
 [ 0,  1, -1,  1,  0,  0,  0,  0,  0,  0],
 [ 0,  0,  0, -1, -1,  1,  0,  0,  0,  0],
 [ 0,  0,  0, -1,  0,  0, -1,  1,  0,  0],
 [ 0,  0,  0,  1,  0,  0,  0, -1,  1,  0],
 [ 0,  0,  0,  0, -1,  0,  0,  0, -1,  1],
 [-1, 1, -1, -1, 1, -2, 1, 5, -7, 1]])

d2 = numpy.linalg.matrix_rank(B)


In [11]:
print(d1)
print(d2)

6
6


complexes: ['S0+E', 'ES0', 'S1+E', 'S1+F', 'FS1', 'S0+F', 'P0+S1', 'S1P0', 'P1+S1', 'P1+F', 'FP1', 'P0+F']
species: ['S0', 'E', 'ES0', 'S1', 'F', 'FS1', 'P0', 'S1P0', 'P1', 'FP1']


In [ ]:
educt_complexes_matrix:
    
[[1 0 0 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 1 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 1 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 1 0 0]
 [0 0 0 0 1 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 1 0 0 0]
 [0 0 0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 0 0 1 1]]


In [12]:
pow(2, 1.1)

2.1435469250725863